name: Build and Upload Singularity Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-singularity:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/franaln/mg-pythia-delphes:3.5.6 -f dockerfiles/mg-pythia-delphes-3.5.6.Dockerfile .

      - name: Install Apptainer (Singularity)
        run: |
          sudo apt-get update
          sudo apt-get install -y apptainer

      - name: Convert Docker image to Singularity .sif
        run: |
          mkdir -p output
          apptainer build output/image.sif docker-daemon://ghcr.io/franaln/mg-pythia-delphes:3.5.6

      - name: Upload .sif to GitHub Packages
        uses: actions/upload-artifact@v4
        with:
          name: singularity-image
          path: output/image.sif

      # Optional: also push the Docker image to GHCR
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image to GHCR
        run: |
          docker push ghcr.io/franaln/mg-pythia-delphes:3.5.6

      - name: Create Release and Upload .sif
        uses: softprops/action-gh-release@v2
        with:
          files: output/image.sif
          tag_name: v${{ github.run_number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}